/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        'on-background': '#151c27',
        surface: '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'on-surface': '#151c27',
        'on-surface-variant': '#464555',
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        secondary: '#006591',
        'on-secondary': '#ffffff',
        'secondary-container': '#39b8fd',
        'on-secondary-container': '#004666',
        tertiary: '#7e3000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a44100',
        'on-tertiary-container': '#ffd2be',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
};
